### ISSUE TITLE
What change must be made to get HTML files instead of DOCX on line 44

### ISSUE THREAD

**Issue by Aaryan-kapur** [machinaeXphilip/docXtoHTML#1]
What change must be made to get HTML files instead of DOCX on line 44

**Comment by machinaeXphilip** [comment]
Hej, thanks for asking. I did not document that very well and will change the README accordingly.

To answer your question:

```js
    if (file.endsWith(".docx")){
        exec("mammoth "+file+" "+file.replace(".docx",".html"));
        console.log("changed "+ file);
    }
 ```
 
 should do the job. i only changed line 44 (the one that starts with exec).

Let me know if that helps and if I can close this issue.

**Comment by machinaeXphilip** [comment]
I updated the code for it is more useful this way.

So if you want you can just do a fresh git clone and it should work.

The old code is now included as a comment on line 44.

Thank you for raising that issue!

**Comment by machinaeXphilip** [comment]
Closing this issue. Seems resolved to me. Feel free to reopen in case of you disagreeing
